version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  springboot-app:
    build: .
    container_name: gdpr_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_HOST: postgres_db
      SPRING_DATASOURCE_PORT: 5432
      SPRING_DATASOURCE_DBNAME: pgdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
