apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gdpr-app-ingress
  namespace: gdpr
spec:
  ingressClassName: nginx
  rules:
    - host: springboot.local
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gdpr-app-api
                port:
                  number: 80